### ISSUE TITLE
Add shebang to make clear if it uses bash or if it is posix complient

### ISSUE THREAD

**Issue by Joshix-1** [schrmh/Helpful-shell-bash-scripts-german#1]

**Comment by schrmh** [comment]
In fact, except for `popoutdisplay_blue` (which has a correct shebang) all scripts should be POSIX-compliant.
Tho I haven't checked it explicitly for every script. It can be done with `checkbashisms -f`.
I might add the shebang to scripts that don't have it when I update them or at some point in the future.

**Comment by schrmh** [comment]
Nvm, fixed with commit https://github.com/schrmh/Helpful-shell-bash-scripts-german/commit/c35ca39c7711efaaac51b592382c5790a8a1f319. Checked all scripts and additionally to the one mentioned, `executedwithinpts2.sh` contains a single bashism (a here string).
